# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 16:37
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='\u6807\u9898')),
                ('description', models.TextField(blank=True, verbose_name='\u63cf\u8ff0')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='\u6807\u7b7e')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='\u5185\u5bb9')),
                ('transshipment', models.URLField(blank=True, verbose_name='\u8f6c\u8f7d\u5730\u5740')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u680f\u76ee\u540d\u79f0')),
            ],
            options={
                'db_table': 'column',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='column',
            field=models.ManyToManyField(to='Article.Column', verbose_name='\u6240\u5c5e\u680f\u76ee'),
        ),
    ]
